apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petisl-notification
  name: petisl-notification
  # namespace: hr-production
spec:
  replicas: 2
  minReadySeconds: 45
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petisl-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: petisl-notification
    spec:
      containers:
      - name: petisl-notification
        image: <IMAGE>
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Africa/Lagos"
        envFrom:
        - secretRef:
            name: mysqldb-user-secret
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      terminationGracePeriodSeconds: 30
