apiVersion: v1
kind: Service
metadata:
  labels:
    app: leasing-notification
  name: leasing-notification
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 8087
  selector:
    app: leasing-notification
